basePath: /v1
definitions:
  model.Card:
    properties:
      art:
        type: string
      id:
        type: integer
      suit:
        $ref: '#/definitions/model.Suit'
      value:
        $ref: '#/definitions/model.CardValue'
    type: object
  model.CardValue:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    type: integer
    x-enum-varnames:
    - Ace
    - Two
    - Three
    - Four
    - Five
    - Six
    - Seven
    - Eight
    - Nine
    - Ten
    - Jack
    - Queen
    - King
    - Joker
  model.Chat:
    properties:
      members:
        items:
          type: integer
        type: array
      messages:
        items:
          $ref: '#/definitions/model.ChatMessage'
        type: array
    type: object
  model.ChatMessage:
    properties:
      message:
        type: string
      sender:
        type: integer
      timestamp:
        type: string
    type: object
  model.History:
    properties:
      losers:
        items:
          type: integer
        type: array
      matchCompletetionDate:
        type: string
      matchId:
        type: integer
      winners:
        items:
          type: integer
        type: array
    type: object
  model.Lobby:
    properties:
      creatationDate:
        type: string
      eloRangeMax:
        type: integer
      eloRangeMin:
        type: integer
      id:
        type: integer
      players:
        items:
          type: integer
        type: array
      privateMatch:
        type: boolean
    type: object
  model.Match:
    properties:
      art:
        type: string
      currentPlayerTurn:
        type: integer
      date:
        items:
          type: string
        type: array
      id:
        type: integer
      lobbyId:
        type: integer
    type: object
  model.Player:
    properties:
      art:
        type: string
      hand:
        items:
          type: integer
        type: array
      id:
        type: integer
      kitty:
        items:
          type: integer
        type: array
      score:
        type: integer
    type: object
  model.Suit:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - Spades
    - Clubs
    - Hearts
    - Diamonds
host: localhost:1323
info:
  contact: {}
  description: cribbage rest server
  title: cribbage server
  version: 0.0.2
paths:
  /admin/card/:
    post:
      consumes:
      - application/json
      parameters:
      - description: card Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Card'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new card
      tags:
      - cards
    put:
      consumes:
      - application/json
      parameters:
      - description: card Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Card'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update card by id
      tags:
      - cards
  /admin/match/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: search for match by barcode
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Match'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get match by barcode
      tags:
      - match
  /card/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: search for card by barcode
        in: query
        name: barcode
        required: true
        type: string
      - description: Store in which the barcode was found
        in: query
        name: storeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Card'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get card by barcode
      tags:
      - cards
  /chat/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: search for chat by barcode
        in: query
        name: barcode
        required: true
        type: string
      - description: Store in which the barcode was found
        in: query
        name: storeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Chat'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get chat by barcode
      tags:
      - chats
    get:
      consumes:
      - application/json
      parameters:
      - description: search for chat by barcode
        in: query
        name: barcode
        required: true
        type: string
      - description: Store in which the barcode was found
        in: query
        name: storeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Chat'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get chat by barcode
      tags:
      - chats
    post:
      consumes:
      - application/json
      parameters:
      - description: chat Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Chat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Chat'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new chat
      tags:
      - chats
    put:
      consumes:
      - application/json
      parameters:
      - description: chat Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Chat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Chat'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update chat by barcode
      tags:
      - chats
  /history/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: search for history by barcode
        in: query
        name: barcode
        required: true
        type: string
      - description: Store in which the barcode was found
        in: query
        name: storeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get history by barcode
      tags:
      - historys
    get:
      consumes:
      - application/json
      parameters:
      - description: search for history by barcode
        in: query
        name: barcode
        required: true
        type: string
      - description: Store in which the barcode was found
        in: query
        name: storeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get history by barcode
      tags:
      - historys
    post:
      consumes:
      - application/json
      parameters:
      - description: history Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.History'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new history
      tags:
      - historys
    put:
      consumes:
      - application/json
      parameters:
      - description: history Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.History'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.History'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update history by barcode
      tags:
      - historys
  /player/card/:
    get:
      consumes:
      - application/json
      parameters:
      - description: search for card by id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Card'
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get card by barcode
      tags:
      - cards
  /player/lobby/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: delete for lobby by id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Lobby'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: delete lobby by id
      tags:
      - lobbys
    get:
      consumes:
      - application/json
      parameters:
      - description: search for id by barcode
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Lobby'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get lobby by id
      tags:
      - lobbys
    post:
      consumes:
      - application/json
      parameters:
      - description: lobby Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Lobby'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Lobby'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new lobby
      tags:
      - lobbys
    put:
      consumes:
      - application/json
      parameters:
      - description: lobby Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Lobby'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Lobby'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update lobby by id
      tags:
      - lobbys
  /player/match/:
    get:
      consumes:
      - application/json
      parameters:
      - description: search for match by barcode
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Match'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get match by barcode
      tags:
      - match
    post:
      consumes:
      - application/json
      parameters:
      - description: match Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Match'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Match'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new match
      tags:
      - match
    put:
      consumes:
      - application/json
      parameters:
      - description: match Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Match'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Match'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update match by barcode
      tags:
      - match
  /player/player/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: search for match by barcode
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get player by barcode
      tags:
      - players
    get:
      consumes:
      - application/json
      parameters:
      - description: search for match by barcode
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get player by barcode
      tags:
      - players
    post:
      consumes:
      - application/json
      parameters:
      - description: player Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Player'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new player
      tags:
      - players
    put:
      consumes:
      - application/json
      parameters:
      - description: player Object to save
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Player'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update player by barcode
      tags:
      - players
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
