basePath: /v1
definitions:
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Int4:
    properties:
      int32:
        type: integer
      valid:
        type: boolean
    type: object
  pgtype.Timestamptz:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        type: string
      valid:
        type: boolean
    type: object
  player.PReady:
    properties:
      matchId:
        description: MatchId
        type: integer
      playerId:
        description: PlayerId
        type: integer
    type: object
  queries.Account:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  queries.Card:
    properties:
      art:
        type: string
      id:
        type: integer
      suit:
        $ref: '#/definitions/queries.Cardsuit'
      value:
        $ref: '#/definitions/queries.Cardvalue'
    type: object
  queries.Cardstate:
    enum:
    - Deck
    - Hand
    - Play
    - Kitty
    type: string
    x-enum-varnames:
    - CardstateDeck
    - CardstateHand
    - CardstatePlay
    - CardstateKitty
  queries.Cardsuit:
    enum:
    - Spades
    - Clubs
    - Hearts
    - Diamonds
    type: string
    x-enum-varnames:
    - CardsuitSpades
    - CardsuitClubs
    - CardsuitHearts
    - CardsuitDiamonds
  queries.Cardvalue:
    enum:
    - Ace
    - Two
    - Three
    - Four
    - Five
    - Six
    - Seven
    - Eight
    - Nine
    - Ten
    - Jack
    - Queen
    - King
    - Joker
    type: string
    x-enum-varnames:
    - CardvalueAce
    - CardvalueTwo
    - CardvalueThree
    - CardvalueFour
    - CardvalueFive
    - CardvalueSix
    - CardvalueSeven
    - CardvalueEight
    - CardvalueNine
    - CardvalueTen
    - CardvalueJack
    - CardvalueQueen
    - CardvalueKing
    - CardvalueJoker
  queries.Deck:
    properties:
      cutmatchcardid:
        $ref: '#/definitions/pgtype.Int4'
      id:
        type: integer
    type: object
  queries.DeckMatchcard:
    properties:
      deckid:
        type: integer
      matchcardid:
        type: integer
    type: object
  queries.Gamestate:
    enum:
    - NewGameState
    - JoinGameState
    - WaitingState
    - MatchReady
    - DealState
    - DiscardState
    - CutState
    - PlayState
    - OpponentState
    - KittyState
    - GameWonState
    - GameLostState
    - MaxGameState
    type: string
    x-enum-varnames:
    - GamestateNewGameState
    - GamestateJoinGameState
    - GamestateWaitingState
    - GamestateMatchReady
    - GamestateDealState
    - GamestateDiscardState
    - GamestateCutState
    - GamestatePlayState
    - GamestateOpponentState
    - GamestateKittyState
    - GamestateGameWonState
    - GamestateGameLostState
    - GamestateMaxGameState
  queries.GetMatchCardsRow:
    properties:
      card:
        $ref: '#/definitions/queries.Card'
      deck:
        $ref: '#/definitions/queries.Deck'
      deckMatchcard:
        $ref: '#/definitions/queries.DeckMatchcard'
      matchcard:
        $ref: '#/definitions/queries.Matchcard'
    type: object
  queries.Match:
    properties:
      art:
        type: string
      creationdate:
        $ref: '#/definitions/pgtype.Timestamptz'
      currentplayerturn:
        type: integer
      cutgamecardid:
        type: integer
      deckid:
        type: integer
      elorangemax:
        type: integer
      elorangemin:
        type: integer
      gamestate:
        $ref: '#/definitions/queries.Gamestate'
      id:
        type: integer
      privatematch:
        type: boolean
      turnpasstimestamps:
        items:
          $ref: '#/definitions/pgtype.Timestamptz'
        type: array
    type: object
  queries.Matchcard:
    properties:
      cardid:
        type: integer
      currowner:
        $ref: '#/definitions/pgtype.Int4'
      id:
        type: integer
      origowner:
        $ref: '#/definitions/pgtype.Int4'
      state:
        $ref: '#/definitions/queries.Cardstate'
    type: object
  queries.Player:
    properties:
      accountid:
        type: integer
      art:
        type: string
      hand:
        items:
          type: integer
        type: array
      id:
        type: integer
      isready:
        type: boolean
      kitty:
        items:
          type: integer
        type: array
      play:
        items:
          type: integer
        type: array
      score:
        type: integer
    type: object
  vo.CutDeckReq:
    properties:
      cutIndex:
        type: string
      matchId:
        type: integer
    type: object
  vo.GameCard:
    properties:
      art:
        type: string
      cardid:
        type: integer
      currowner:
        $ref: '#/definitions/pgtype.Int4'
      id:
        type: integer
      origowner:
        $ref: '#/definitions/pgtype.Int4'
      state:
        $ref: '#/definitions/queries.Cardstate'
      suit:
        $ref: '#/definitions/queries.Cardsuit'
      value:
        $ref: '#/definitions/queries.Cardvalue'
    type: object
  vo.GameDeck:
    properties:
      cards:
        items:
          $ref: '#/definitions/vo.GameCard'
        type: array
      cutmatchcardid:
        $ref: '#/definitions/pgtype.Int4'
      id:
        type: integer
    type: object
  vo.GameMatch:
    properties:
      art:
        type: string
      creationdate:
        $ref: '#/definitions/pgtype.Timestamptz'
      currentplayerturn:
        type: integer
      cutgamecardid:
        type: integer
      deckid:
        type: integer
      elorangemax:
        type: integer
      elorangemin:
        type: integer
      gamestate:
        $ref: '#/definitions/queries.Gamestate'
      id:
        type: integer
      players:
        items:
          $ref: '#/definitions/queries.Player'
        type: array
      privatematch:
        type: boolean
      turnpasstimestamps:
        items:
          $ref: '#/definitions/pgtype.Timestamptz'
        type: array
    type: object
  vo.HandModifier:
    properties:
      cardIds:
        items:
          type: integer
        type: array
      matchId:
        type: integer
      playerId:
        type: integer
    type: object
  vo.JoinMatchReq:
    properties:
      accountId:
        type: integer
      matchId:
        type: integer
    type: object
  vo.MatchDetailsResponse:
    properties:
      gameState:
        $ref: '#/definitions/queries.Gamestate'
      matchId:
        type: integer
      playerId:
        type: integer
    type: object
  vo.MatchRequirements:
    properties:
      accountId:
        type: integer
      eloRangeMax:
        type: integer
      eloRangeMin:
        type: integer
      isPrivate:
        type: boolean
    type: object
host: localhost:1323
info:
  contact: {}
  description: cribbage rest server
  title: cribbage server
  version: 0.0.4
paths:
  /account/login/:
    post:
      consumes:
      - application/json
      parameters:
      - description: id to login with
        in: body
        name: details
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Account'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Login
      tags:
      - account
  /deck/:
    get:
      consumes:
      - application/json
      parameters:
      - description: search for deck by match id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.GameDeck'
        "404":
          description: Not Found
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
      summary: Get deck by match id
      tags:
      - deck
  /match/:
    get:
      consumes:
      - application/json
      parameters:
      - description: match id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.MatchDetailsResponse'
        "404":
          description: Not Found
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
      summary: Get match state by match id
      tags:
      - match
    post:
      consumes:
      - application/json
      parameters:
      - description: MatchRequirements
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/vo.MatchRequirements'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new match
      tags:
      - match
  /match/cards/:
    get:
      consumes:
      - application/json
      parameters:
      - description: match id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/queries.GetMatchCardsRow'
            type: array
        "404":
          description: Not Found
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
      summary: Get match cards by match id
      tags:
      - match
  /match/cut:
    put:
      consumes:
      - application/json
      parameters:
      - description: Deck index that is to become the cut
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/vo.CutDeckReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Cut deck by index of card selected
      tags:
      - match
  /match/join:
    put:
      consumes:
      - application/json
      parameters:
      - description: JoinMatchReq object
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/vo.JoinMatchReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.MatchDetailsResponse'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Join match by id
      tags:
      - match
  /match/player/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: search for match by barcode
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get player by barcode
      tags:
      - players
    get:
      consumes:
      - application/json
      parameters:
      - description: search for match by id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get player by barcode
      tags:
      - players
    post:
      consumes:
      - application/json
      parameters:
      - description: player Object to save
        in: body
        name: details
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Player'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new player
      tags:
      - players
  /match/player//kitty:
    put:
      consumes:
      - application/json
      parameters:
      - description: array of ids to add to kitty
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/vo.HandModifier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Match'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update kitty with ids
      tags:
      - match
  /match/player/ready:
    put:
      consumes:
      - application/json
      parameters:
      - description: player id to update
        in: body
        name: pReady
        required: true
        schema:
          $ref: '#/definitions/player.PReady'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update player by id to be ready. Returns true if all players are ready
      tags:
      - players
  /matches/open:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/vo.GameMatch'
            type: array
        "404":
          description: Not Found
          schema: {}
        "422":
          description: Unprocessable Entity
          schema: {}
      summary: Get match by id
      tags:
      - match
  /play:
    put:
      consumes:
      - application/json
      parameters:
      - description: HandModifier object
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/vo.HandModifier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Match'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update play
      tags:
      - match
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
