services:
  cribbage-server:
    profiles: [game, default]
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 1323:1323
  db:
    profiles: [db, default]
    image: postgres:16.2-bullseye
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cribbage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  adminer:
    profiles: [db, default]
    image: adminer
    restart: always
    ports:
      - 8080:8080